{% set version = "0.3.6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-isa2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/isa2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/isa2/isa2_{{ version }}.tar.gz
  sha256: 6256da84dd9a10499f802838c2065ee6e4dcc012b07d21116496ff8aebb65c66

build:
  merge_build_host: true  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib('m2w64_c') }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-lattice
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-lattice

test:
  commands:
    - $R -e "library('isa2')"           # [not win]
    - "\"%R%\" -e \"library('isa2')\""  # [win]

about:
  home: https://github.com/gaborcsardi/ISA
  license: CC-BY-NC-SA-4.0
  summary: The ISA is a biclustering algorithm that finds modules  in an input matrix. A module or bicluster is a block of the reordered input matrix.
  license_family: CC
  license_file:
    - LICENSE-CC-BY-NC-SA-4

extra:
  recipe-maintainers:
    - conda-forge/r
